# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for Oncology Interactive Handbook desktop .exe."""

import sys
from pathlib import Path

_root = Path(SPECPATH).resolve()
_site_pkgs = Path(sys.executable).parent / "Lib" / "site-packages"

a = Analysis(
    [str(_root / "desktop_launcher.py")],
    pathex=[str(_root)],
    binaries=[],
    datas=[
        (str(_root / "data"), "data"),
        (str(_root / "app" / "assets"), "app/assets"),
        (str(_site_pkgs / "dash_mantine_components" / "package-info.json"), "dash_mantine_components"),
        (str(_site_pkgs / "dash_cytoscape" / "metadata.json"), "dash_cytoscape"),
        (str(_site_pkgs / "dash_cytoscape" / "package.json"), "dash_cytoscape"),
    ],
    hiddenimports=[
        "dash",
        "dash_bootstrap_components",
        "dash_mantine_components",
        "dash_cytoscape",
        "plotly",
        "plotly.express",
        "plotly.graph_objects",
        "pandas",
        "flask",
        "openai",
        "dotenv",
        "orjson",
        "requests",
        "numpy",
        "packaging",
        "dash._callback",
        "dash.backends",
        "dash.backends._flask",
        "dash.dcc",
        "dash.html",
        "app",
        "app.main",
        "app.layout",
        "app.config",
        "app.callbacks",
        "app.pages",
        "app.pages.home",
        "app.pages.disease",
        "app.pages.regimens",
        "app.pages.trials",
        "app.components",
        "app.components.cards",
        "app.components.tables",
        "app.components.filters",
        "app.components.callouts",
        "app.components.navigation",
        "app.components.staging_viewer",
        "app.components.section_renderer",
        "app.components.handbook_renderers",
        "app.components.trial_viz",
        "app.components.viz",
        "app.components.viz.charts",
        "app.components.viz.dashboards",
        "app.components.viz.pathways",
        "app.data",
        "app.data.loader",
        "app.data.schemas",
        "app.data.transforms",
        "app.data.category_map",
        "app.data.definition_rewriter",
        "app.data.section_rewriter",
        "app.data.rewriters",
        "app.data.rewriters.base",
        "app.data.rewriters.prompts",
        "app.data.rewriters.rewrite_all",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter",
        "IPython",
        "jupyter",
        "notebook",
        "matplotlib",
        "scipy",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="oncology_handbook_v3",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
